### ISSUE TITLE
Hadoop "Ready State" Prep

### ISSUE THREAD

**Issue by cloudedge** [opencrowbar/core#150]
The Hadoop readiness barclamp is responsible for transitioning nodes
from the base opencrowbar state to a state ready for an Apache
Hadoop installation.

Requirements
------------

General:
    * Hadoop distro agnostic

Supported Node Roles:
    * Hadoop Data node
    * Hadoop Infrastructure node (name node, resource manager, etc)
    * Hadoop edge or gateway node

Storage:
    * Format and create filesystems on data disks
    * mount disks using Hadoop naming convention (/data/<n>) 
    * mount disks with appropriate options (noatime, etc)
    * create necessary directories with correct permissions 

Operating System:
    * create core users and groups (hdfs, etc)
    * configure ulimits
    * set OS Kernel options (e.g. thp compaction, selinux, swapping)

Networking:
    * configure interface bonding and mode
    * configure network MTU
    * check / configure firewall 

Anti-Requirements:
    * will not install JDK / JVM (licensing, version dependencies)
    * will not stage or install any Hadoop distro

**Comment by galthaus** [comment]
Not sure we are going to do this in opencrowbar core.

**Comment by galthaus** [comment]
Closing this for core.
