### ISSUE TITLE
OpenStack Icehouse Upstreams (from Ready State)

### ISSUE THREAD

**Issue by cloudedge** [opencrowbar/core#154]
note: about getting Ready State for upstreams NOT advantaging CB ahead of upstream.  some work will be needed in upstreams

As an operator, I want to be able to use Crowbar to drive the Icehouse OpenStack Chef Upsteams.  While I would like to have many cookbooks, I am ok to start with Nova, Keystone, Glance, Cinder, Horizon, Neutron ML2+VXLAN, Support Infra (Database & Messaging). My priority is to be able to use the upstreams first and then work in the community to help them mature.  I have no interest in getting them from a single vendor or being tied to a single OS.  For that reason, I expect them to work on at least Ubuntu and Centos.

Review: Neutron GRE vs VXLAN?   If VXLAN requires switch support than we will revisit. 

Overtime, I'd like to have (in order)
* a default HA configuration.
* Heat
* Use the Ceph deploy as the storage target

Architecture:

As an operator, I expect that the 
* controller nodes will be setup with RAID5 and standard BIOS.  
* Compute nodes will use RAID10 with virtualization enabled.  
* Storage nodes will use JBOD with standard BIOS.  
* I also expect admin, public, private and storage networks to be configured.  The transport networks should use teamed NICs.  

Preq: Needs to be able to use Chef server because upstreams assume encrypted databags.

**Comment by galthaus** [comment]
Closing for non-core reasons.

**Comment by sjensen** [comment]
markling wontfix
