### ISSUE TITLE
Convert documentation from Markdown to Restructured Text (includes removing doc code)

### ISSUE THREAD

**Issue by lhrc-mikeyp** [opencrowbar/core#214]
As developers, we are hitting the limits of markdown and our integrated documentation system, making it difficult to develop, maintain, and publish documentation.  We would like to improve the documentation system so it is easier to develop documentation and publish it in multiple formats.

The main parts of this proposal are:
 - Convert existing documentation in the doc subdirectory from Markdown to Restructured text format
 - Publish the documentation to crowbar.readthedocs.org automatically
 - Update documentation on the documentation process
 - Remove the existing documentation processing and rendering code in opencrowbar
 - Make it possible to develop and test documentation locally before commits

**Comment by galthaus** [comment]
Closing - we should reopen this one day when we are more focused on it.
