### ISSUE TITLE
Available OS noderole is failing

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#299]
Logs show that we are pulling a file from Amazon but I do not have access to the internet from the container.  More than likely it is a requirement but I wanted to log it.

![image](https://cloud.githubusercontent.com/assets/1200679/4892127/eeb236e4-63ae-11e4-8d4e-f82e198c584b.png)

**Comment by galthaus** [comment]
I think this is resolved.

**Comment by galthaus** [comment]
I think this has been resolved along the way..  Not sure when.

**Comment by sjensen** [comment]
Agreed it is resolved along the way.  Nice to have a Blue Bird every once and a while
