### ISSUE TITLE
Admin annealing fails

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#336]
Version 2.0.0.4293.1

Chef Server Role

Clean CentOS 6.5 installation fails with...

//tmp/scriptjig-EUKiTW/chef-server/01-install-chef-server.sh@254(): echo 'Creating chef client for Crowbar on admin node'
Creating chef client for Crowbar on admin node
//tmp/scriptjig-EUKiTW/chef-server/01-install-chef-server.sh@255(): mkdir /home/crowbar/.chef
mkdir: cannot create directory `/home/crowbar/.chef': File exists
/tmp/scriptjig-EUKiTW/runner@58(): exit 1

Err: Warning: Permanently added 'fc1d:41b7:980a:1:2bdf:fd1e:6a3e:96eb' (RSA) to the list of known hosts.

**Comment by galthaus** [comment]
Did this happen because production.sh was run twice?

**Comment by sjensen** [comment]
Do not think so.  Will rerun today

**Comment by sjensen** [comment]
Same Error...

which: no chef-client in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin)
//tmp/scriptjig-KsiOQs/chef-client/01-install-client.sh@4(): [[ -f /etc/redhat-release ]]
//tmp/scriptjig-KsiOQs/chef-client/01-install-client.sh@5(): yum -y makecache
Loaded plugins: security
Metadata Cache Created
//tmp/scriptjig-KsiOQs/chef-client/01-install-client.sh@6(): yum install -y chef
Loaded plugins: security
Setting up Install Process
No package chef available.
Error: Nothing to do
/tmp/scriptjig-KsiOQs/runner@58(): exit 1

Err: Warning: Permanently added '192.168.124.82' (RSA) to the list of known hosts.

**Comment by galthaus** [comment]
I think this latest error is the error for #454.  This original was a centos-6.5 admin node install error.

**Comment by sjensen** [comment]
OOPSIE you are right.  Crossed the streams
