### ISSUE TITLE
Alias does not update DNS

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#342]
Updated Alais of a system PRIOR to installing the OS.  This should cause DNS to be updates so that the system is reachable via the alias

**Comment by ravolt** [comment]
Not a bug.  You need to give the FQDN w/ the alias + retry on the DNS A Records

**Comment by galthaus** [comment]
I think question is: does setting alias validate that FQDN is present?
The next question is: should the system automatically re-run the DNS A Records node role?

I think both should be addressed with some coming work around DNS and networks.

**Comment by zehicle** [comment]
1) we got right of Alias - that was bogus
2) we created the whole DNS feature #677 that handles this MUCH better
