### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#360]
reating machine-install user
{
  "id": 2,
  "email": "root@localhost.localdomain",
  "username": "machine-install",
  "is_admin": false,
  "created_at": "2015-01-06T17:07:33.631Z",
  "updated_at": "2015-01-06T17:07:33.639Z"
}
Tue Jan  6 12:07:33 EST 2015
sed: can't read /etc/hos: No such file or directory

Looks like a typo installation fails

**Comment by galthaus** [comment]
This was fixed by a previous pull request.
