### ISSUE TITLE
Log the installation

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#361]
When running production.sh to run the install I need a log to review if a user has an issue.  should probably be in /var/log/crowbar/install.log

**Comment by galthaus** [comment]
Captured some of the logs.  Should we do more?

**Comment by galthaus** [comment]
The logs are placed in /opt/opencrowbar/core because /var/log/crowbar doesn't exist yet.

**Comment by sjensen** [comment]
Works for me
