### ISSUE TITLE
centos not matching os_support correctly

### ISSUE THREAD

**Issue by dack** [opencrowbar/core#368]
production.sh fails on centos 7, with an error that the os is unsupported. adding "centos-7.0.1406" to the os_support list in crowbar.yml resolves the error. centos-7.0 is already in the list, but it appears the ".1406" is required for it to match correctly.

**Comment by VictorLowther** [comment]
Patch?

**Comment by dack** [comment]
Never mind - I see it was actually fixed a few weeks ago. I guess I was not looking at the latest version from github.
