### ISSUE TITLE
Network Range API has issues

### ISSUE THREAD

**Issue by galthaus** [opencrowbar/core#383]
1. crowbar cli doesn't have a processor for it.
2. the json returned for ranges is not consistent.  The first/last are strings everywhere except in the reply json of a list.  They should be strings.
3. The show function returns a list.  It should return one.
4. The show function expects a network id.  It should take either an id or a network_id and a name.
5. The routes need to be examined to allow multiple paths.
6. Update/Add tests!

**Comment by VictorLowther** [comment]
#590 addresses this from the API and CLI side.

**Comment by sjensen** [comment]
Can I please get an example of a CLI cmd which will show this?  Latest install does not have any cmds that seem to show this information

**Comment by VictorLowther** [comment]
crowbar networkranges <command>

crowbar <objectclass> help shows all the commands that are available for <objectclass>, and crowbar help shows all the objectclass/command combinations.
