### ISSUE TITLE
nodes do not always reboot for deployment after OS install

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#387]
When I create a new deploy and add saltstack/packstack

I expect the node to reboot into its OS before installing saltstack/packstack

Instead, the node stays in sledgehammer and tries to install saltstack/packstack, which results in a read-only filesystem error.

Manually rebooting the nodes fixes this issue (note, for some reason the power control buttons on the nodes doesn't work, so I use ipmitool in the CLI)

**Comment by ravolt** [comment]
I am not seeing this anymore.  @dudymas, please confirm its still an issue

**Comment by dudymas** [comment]
This has been fixed... I'm not sure what did it. But all is well. Closing

**Comment by sjensen** [comment]
Marking tested due to @dudymas comments as well as some internal verification by me
