### ISSUE TITLE
CentOS 6.6 deployment fails (following deployment guide)

### ISSUE THREAD

**Issue by dack** [opencrowbar/core#391]
When following the latest deployment guide (Install-CentOS-RHEL-6.6-AdminNode.md), production.sh fails with the error shown below. This is on a fresh install of CentOS 6.6 with all updates installed, using the RPMs installed via crowbar-install.sh.

```
  ================================================================================
  Recipe Compile Error in /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb
  ================================================================================

  RuntimeError
  ------------
  Cannot install crowbar on centos-6.6!  Can only install on one of ubuntu-12.04 redhat-6.5 centos-6.5 centos-7.0 opensuse-13.1 fedora-20

  Cookbook Trace:
  ---------------
    /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb:40:in `from_file'

  Relevant File Content:
  ----------------------
  /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb:

   33:                when "debian","ubuntu" then "debs"
   34:                when "centos","redhat","opensuse","suse","fedora" then "rpms"
   35:                else
   36:                  raise "Cannot figure out what package type we should use!"
   37:                end
   38:
   39:  unless prereqs["os_support"].member?(os_token)
   40>>   raise "Cannot install crowbar on #{os_token}!  Can only install on one of #{prereqs["os_support"].join(" ")}"
   41:  end
   42:
   43:  tftproot = "/tftpboot"
   44:  sledgehammer_url="http://opencrowbar.s3-website-us-east-1.amazonaws.com/sledgehammer/#{sledgehammer_signature}"
   45:  sledgehammer_dir="#{tftproot}/sledgehammer/#{sledgehammer_signature}"
   46:
   47:  repos = []
   48:  pkgs = []
   49:  raw_pkgs = []


  Running handlers:
[2015-01-23T16:37:21-08:00] ERROR: Running exception handlers
  Running handlers complete
[2015-01-23T16:37:21-08:00] ERROR: Exception handlers complete
[2015-01-23T16:37:21-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
  Chef Client failed. 4 resources updated in 47.480207633 seconds
[2015-01-23T16:37:21-08:00] ERROR: Cannot install crowbar on centos-6.6!  Can only install on one of ubuntu-12.04 redhat-6.5 centos-6.5 centos-7.0 opensuse-13.1                                                                       fedora-20
[2015-01-23T16:37:21-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef-solo bootstrap run failed

```

**Comment by galthaus** [comment]
My guess is that you need to add the --develop flag for the CentOS 6.6 base system.  The documentation mentions it, but it is probably not explicit enough.  The current support admin node OSes are CentOS 6.5 for the RPMs based on the master tree (without the --develop flag) and CentOS 6.6 for the RPMs based on the develop tree (with the --develop flag).

**Comment by cloudedge** [comment]
I believe admin install on Cent 6.6 support was added in the develop
branch, not in the Broom/2.1 release which is current master.

Adding Scott to verify.

On Fri, Jan 23, 2015 at 6:45 PM, dack <notifications@github.com> wrote:

> When following the latest deployment guide (
> Install-CentOS-RHEL-6.6-AdminNode.md), production.sh fails with the error
> shown below. This is on a fresh install of CentOS 6.6 with all updates
> installed, using the RPMs installed via crowbar-install.sh.
>
>   ================================================================================
>   Recipe Compile Error in /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb
>   ================================================================================
>
>   RuntimeError
>   ------------
>   Cannot install crowbar on centos-6.6!  Can only install on one of ubuntu-12.04 redhat-6.5 centos-6.5 centos-7.0 opensuse-13.1 fedora-20
>
>   Cookbook Trace:
>   ---------------
>     /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb:40:in `from_file'
>
>   Relevant File Content:
>   ----------------------
>   /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb:
>
>    33:                when "debian","ubuntu" then "debs"
>    34:                when "centos","redhat","opensuse","suse","fedora" then "rpms"
>    35:                else
>    36:                  raise "Cannot figure out what package type we should use!"
>    37:                end
>    38:
>    39:  unless prereqs["os_support"].member?(os_token)
>    40>>   raise "Cannot install crowbar on #{os_token}!  Can only install on one of #{prereqs["os_support"].join(" ")}"
>    41:  end
>    42:
>    43:  tftproot = "/tftpboot"
>    44:  sledgehammer_url="http://opencrowbar.s3-website-us-east-1.amazonaws.com/sledgehammer/#{sledgehammer_signature}"
>    45:  sledgehammer_dir="#{tftproot}/sledgehammer/#{sledgehammer_signature}"
>    46:
>    47:  repos = []
>    48:  pkgs = []
>    49:  raw_pkgs = []
>
>
>   Running handlers:
> [2015-01-23T16:37:21-08:00] ERROR: Running exception handlers
>   Running handlers complete
> [2015-01-23T16:37:21-08:00] ERROR: Exception handlers complete
> [2015-01-23T16:37:21-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
>   Chef Client failed. 4 resources updated in 47.480207633 seconds
> [2015-01-23T16:37:21-08:00] ERROR: Cannot install crowbar on centos-6.6!  Can only install on one of ubuntu-12.04 redhat-6.5 centos-6.5 centos-7.0 opensuse-13.1                                                                       fedora-20
> [2015-01-23T16:37:21-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
> Chef-solo bootstrap run failed
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencrowbar/core/issues/391>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by cloudedge** [comment]
That is correct. Broom (v2.1) which is released supports CentOS 6.5.
Camshaft which is currently under development Supports 6.6

-Scott

On Saturday, January 24, 2015, Rob Hirschfeld <rob@rackn.com> wrote:

> I believe admin install on Cent 6.6 support was added in the develop
> branch, not in the Broom/2.1 release which is current master.
>
> Adding Scott to verify.
>
> On Fri, Jan 23, 2015 at 6:45 PM, dack <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> When following the latest deployment guide (
>> Install-CentOS-RHEL-6.6-AdminNode.md), production.sh fails with the
>> error shown below. This is on a fresh install of CentOS 6.6 with all
>> updates installed, using the RPMs installed via crowbar-install.sh.
>>
>>   ================================================================================
>>   Recipe Compile Error in /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb
>>   ================================================================================
>>
>>   RuntimeError
>>   ------------
>>   Cannot install crowbar on centos-6.6!  Can only install on one of ubuntu-12.04 redhat-6.5 centos-6.5 centos-7.0 opensuse-13.1 fedora-20
>>
>>   Cookbook Trace:
>>   ---------------
>>     /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb:40:in `from_file'
>>
>>   Relevant File Content:
>>   ----------------------
>>   /opt/opencrowbar/core/chef/cookbooks/crowbar-bootstrap/recipes/default.rb:
>>
>>    33:                when "debian","ubuntu" then "debs"
>>    34:                when "centos","redhat","opensuse","suse","fedora" then "rpms"
>>    35:                else
>>    36:                  raise "Cannot figure out what package type we should use!"
>>    37:                end
>>    38:
>>    39:  unless prereqs["os_support"].member?(os_token)
>>    40>>   raise "Cannot install crowbar on #{os_token}!  Can only install on one of #{prereqs["os_support"].join(" ")}"
>>    41:  end
>>    42:
>>    43:  tftproot = "/tftpboot"
>>    44:  sledgehammer_url="http://opencrowbar.s3-website-us-east-1.amazonaws.com/sledgehammer/#{sledgehammer_signature}"
>>    45:  sledgehammer_dir="#{tftproot}/sledgehammer/#{sledgehammer_signature}"
>>    46:
>>    47:  repos = []
>>    48:  pkgs = []
>>    49:  raw_pkgs = []
>>
>>
>>   Running handlers:
>> [2015-01-23T16:37:21-08:00] ERROR: Running exception handlers
>>   Running handlers complete
>> [2015-01-23T16:37:21-08:00] ERROR: Exception handlers complete
>> [2015-01-23T16:37:21-08:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
>>   Chef Client failed. 4 resources updated in 47.480207633 seconds
>> [2015-01-23T16:37:21-08:00] ERROR: Cannot install crowbar on centos-6.6!  Can only install on one of ubuntu-12.04 redhat-6.5 centos-6.5 centos-7.0 opensuse-13.1                                                                       fedora-20
>> [2015-01-23T16:37:21-08:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>> Chef-solo bootstrap run failed
>>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/opencrowbar/core/issues/391>.
>>
>
>
>
> --
> Rob
> ____________________________
> Rob Hirschfeld, 512-773-7522
> RackN CEO/Founder (rob@rackn.com
> <javascript:_e(%7B%7D,'cvml','rob@rackn.com');>)
>
> I am in CENTRAL (-6) time
> http://robhirschfeld.com
> twitter: @zehicle, github: cloudedge & ravolt
>


-- 
Scott Jensen
Founder and COO
RackN, Inc.
(603) 438-3087

**Comment by dack** [comment]
Got it, thanks! It might be worthwhile to add something to the deployment guide to say which OS's are currently support on develop vs release.

**Comment by galthaus** [comment]
I did try that and it is kinda there though not in a way that makes sense to people other than me.  :-) and :-(

Let's us this to update that docs.

**Comment by galthaus** [comment]
Updated docs.

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6cz9q2-7c&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=QsYhg3PD&invitationId=6118771214593908736








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6cz9q2-7c&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGohm1acD8WhgAAAVOo-GxyBFyflKp3JtW6csoYneuQXzplObQYb5sX7LdWdKDGOvaWx2Vx7k7VdPqg3z_WNqgp1BhF6fH37bOzukO1xBUIWDP0BjgIEHGmglTkzQDy63aJp_Jufv9n7SJ1uQehNxj30HI0ksUuUn9EUHq_s7MupPJbunLJG6M-3UQkcgXdajzo&eid=0-im6cz9q2-7c


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6cz9q2-7c&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=t81cbz-imfau3a7-dd&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=QsYhg3PD&invitationID=6118771214593908736

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=t81cbz-imfau3a7-dd&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=QsYhg3PD&invitationID=6118771214593908736





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=t81cbz-imfau3a7-dd&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=t81cbz-imfau3a7-dd&loid=AQGjYXB2pxu1hwAAAVPJ-d-H-o8PD4BsqML3SXyReRa3JT7up4ouTWxlFPtCfFOwnuEuxBnmkKkUQ3Pm5-DyT8cGWef3pW1VlPXzXCWd6wz3bPSKc9MXnQzhjvSf6s9qNOwLvoQ0vbKuWtoEeCHqvASAWHn544wSOOTapZbPU9spSsNEvCq-8TBclsh_NiQjKkfx

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=t81cbz-imfau3a7-dd&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=t81cbz-impb4wtg-py&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=QsYhg3PD&invitationID=6118771214593908736

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=t81cbz-impb4wtg-py&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=QsYhg3PD&invitationID=6118771214593908736





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=t81cbz-impb4wtg-py&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=t81cbz-impb4wtg-py&loid=AQGk5plITuKVSwAAAVPuBMO9guFsx_1LHFvs4svAKkFk2Vzro9m7FXVMQMc-PX4iiQTtJsQRPNfiBojssmarZVkC9S_Q0mqBuVWlSBI91XOqAMHlf0VcJyDDce78hZFUkFUtHm5uN6N0aWy2EJ9pWuv4pe2jmxKQO4-3qCaFTRgx_yrGF57MPYDrfXUV1RXv1nJx

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=t81cbz-impb4wtg-py&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
