### ISSUE TITLE
RPM install with --devel changes sshd_config

### ISSUE THREAD

**Issue by bvierra** [opencrowbar/core#395]
Using the instructions at: https://github.com/opencrowbar/core/blob/develop/doc/deployment-guide/Install-CentOS-RHEL-6.6-AdminNode.md the sshd_config is changed. Since I was doing a test install and was not worried about security I was running as root without a key (just wanted to get something up and running).

You change PermitRootLogin to "PermitRootLogin without-password" which effectively locked me out. Please do not do this by default, the basic hardening of the server should be done via the admin separate from the program installation.

**Comment by galthaus** [comment]
Another option is to setup the crowbar user with password access earlier in the process.

**Comment by galthaus** [comment]
When the sshd config is changed, the very next action is to add the crowbar user with password crowbar.  So, we apparently already do this.  We may want to make the crowbar user first and then sshd bounce.

**Comment by galthaus** [comment]
Actaully, we config sshd, but don't restart until we have the crowbar user in place.  So, this is already in place.

**Comment by galthaus** [comment]
Updated docs for 6.6 admin node install to reflect the crowbar user option and cleaned up the text that a community added about a new account or key setup.

**Comment by sjensen** [comment]
@bvierra Is this acceptable?
