### ISSUE TITLE
Destroying a node should allow it to be discovered again

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#416]
Given two deployments, one which had 3 supermicros with cent7/packstack/saltstack,
Let's say I destroy one of the nodes.

I expect that destroying a node from a deployment should allow me to re-discover and configure the node.

Instead the node fails to PXE boot, reporting that no boot image came back.
![screen shot 2015-02-03 at 11 37 51 am](https://cloud.githubusercontent.com/assets/928448/6024444/43378ca0-ab99-11e4-9c25-e626e2bd1f7e.png)

**Comment by ravolt** [comment]
duplicated this

**Comment by dudymas** [comment]
I'm researching it now... let me know if you wanted me to test some things out... I still have that blade and can do a lot of boot tests on it

**Comment by galthaus** [comment]
I think I've resolved this with #456 in conjunction with some work @ravolt had already done.
