### ISSUE TITLE
System no longer recognizes CentOS 6.5 as an OS to be deployed

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#418]
CentOS 6.5 is not available for deployment even if the .iso is staged

**Comment by sjensen** [comment]
New issue when selecting 6.5 from the wizard

Attrib provisioner-target_os: New requested data "centos-6.5" failed schema validation [/provisioner-target_os]: 'centos-6.5': invalid provisioner-target_os value.

Error Backtrace
/opt/opencrowbar/core/rails/app/models/attrib.rb:186:in `kwalify_validate'
/opt/opencrowbar/core/rails/app/models/attrib.rb:214:in `__set'
/opt/opencrowbar/core/rails/app/models/attrib.rb:155:in `set'
/opt/opencrowbar/core/rails/app/models/attrib.rb:159:in `set'
/opt/opencrowbar/core/rails/app/controllers/dashboard_controller.rb:139:in `block in getready'
/opt/opencrowbar/core/rails/app/controllers/dashboard_controller.rb:127:in `each'
/opt/opencrowbar/core/rails/app/controllers/dashboard_controller.rb:127:in `getready'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:189:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:423:in `_run__2726325706840934253__process_action__callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/callbacks.rb:17:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `block in instrument'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/notifications.rb:159:in `instrument'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/base.rb:136:in `process'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/abstract_controller/rendering.rb:44:in `process'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:195:in `dispatch'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_controller/metal.rb:231:in `block in action'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:50:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:71:in `block in call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `each'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/journey/router.rb:59:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/routing/route_set.rb:676:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:35:in `block in call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `catch'
/var/cache/crowbar/gems/ruby/2.1.0/gems/warden-1.2.3/lib/warden/manager.rb:34:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/flash.rb:241:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/cookies.rb:486:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/query_cache.rb:36:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activerecord-4.0.13/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:373:in `_run__1447345631916354355__call__callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/callbacks.rb:80:in `run_callbacks'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:38:in `call_app'
/var/cache/crowbar/gems/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `block in call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/cache/crowbar/gems/ruby/2.1.0/gems/railties-4.0.13/lib/rails/rack/logger.rb:20:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/activesupport-4.0.13/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/actionpack-4.0.13/lib/action_dispatch/middleware/static.rb:84:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/railties-4.0.13/lib/rails/engine.rb:511:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/railties-4.0.13/lib/rails/application.rb:97:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/railties-4.0.13/lib/rails/railtie/configurable.rb:30:in `method_missing'
/var/cache/crowbar/gems/ruby/2.1.0/gems/puma-2.11.0/lib/puma/configuration.rb:82:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:507:in `handle_request'
/var/cache/crowbar/gems/ruby/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:375:in `process_client'
/var/cache/crowbar/gems/ruby/2.1.0/gems/puma-2.11.0/lib/puma/server.rb:262:in `block in run'
/var/cache/crowbar/gems/ruby/2.1.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `call'
/var/cache/crowbar/gems/ruby/2.1.0/gems/puma-2.11.0/lib/puma/thread_pool.rb:104:in `block in spawn_thread'

**Comment by sjensen** [comment]
Deploying 6.5 is causing a boot loop where the system does not ever install the OS

**Comment by galthaus** [comment]
Fixed by #419
