### ISSUE TITLE
calling power reset on crowbar CLI does not work

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#430]
Given 8 nodes, with ids 1-8,
I call:
```bash
$ crowbar nodes power 7 reset
```

Regardless of the state of that node, I expect the  node to reboot.

Instead I get this result:
```bash
[crowbar@1835a2a13229 core]$ crowbar nodes power 7 reset
{
  "id": 7,
  "action": "reset",
  "result": false
}
```

Additionally, this came about because I was trying to reset the machine from the web UI, however that does not work as well.

I also noticed that the account that crowbar created on the device has no permissions to reset:
```bash
[crowbar@1835a2a13229 core]$ ipmitool -H 10.0.45.46 -U root -P <the password> power reset
Get Session Challenge command failed: Invalid data field in request
```

Lastly, if I make the same ipmitool command with my own ipmi account and password, the node resets successfully.

**Comment by galthaus** [comment]
Maybe hardware specific issues (IPMI quirks may be needed).

**Comment by galthaus** [comment]
Can you add specifics about the failing hardware?  Ipmitool mc info would be helpful.

**Comment by sjensen** [comment]
Seems to work correctly now!

**Comment by dudymas** [comment]
Forgot to add I concur... this works fine for me now.
