### ISSUE TITLE
chef-client role stuck in 'To Do'

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#431]
Given two deployments with three nodes each,

I assign packstack and saltstack to all six nodes across both deployments.

I expect the nodes to boot back up with centos7 and start installing.

Instead, only four nodes finish booting and running. The other two nodes (both packstack base nodes) are stuck at 'chef-client':

![screen shot 2015-02-05 at 4 06 19 pm](https://cloud.githubusercontent.com/assets/928448/6069329/74940152-ad51-11e4-9047-b963bd2774b5.png)

The system deployment shows that the next step should be good:
![screen shot 2015-02-05 at 4 10 48 pm](https://cloud.githubusercontent.com/assets/928448/6069356/9474058a-ad51-11e4-9d7d-69036967e989.png)

If I 'retry' the chef-server step, the chef client steps block, but when it finishes, they go back to 'To Do'

The logs don't list any errors, and I just see the delayed jobs doing updates like normal.

Also, here's one of the nodes, just to show that it's working and up:
![screen shot 2015-02-05 at 4 18 23 pm](https://cloud.githubusercontent.com/assets/928448/6069494/bc4d5718-ad52-11e4-84a3-f3d66361ddf7.png)

Cent7 appears to have installed just fine.

**Comment by ravolt** [comment]
what happens if you restart the crowbar servce?

**Comment by dudymas** [comment]
I'll try that tonight, but I just wanted to say I rebuilt the server three times and did about 9 deployments... and in all my testing, the issue can be avoided by booting one node at a time... if you do more than one at a time, the issue starts to occur.

Again, I'll try restarting the crowbar service tonight... I have a very strong hunch that'll fix this

**Comment by galthaus** [comment]
Still there and could be related to DNS issues.

**Comment by galthaus** [comment]
I need to figure out how to replicate this more. 
I'm not going to hold camshaft for this.

**Comment by dudymas** [comment]
I just updated and I'm not getting this anymore either.

**Comment by dudymas** [comment]
Cannot reproduce. Likely fixed with other updates and bug-fixes.
