### ISSUE TITLE
Server type (UI Change)

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#444]
Please change the OpenCrowbar UI to specify the node type at the top of the device.  i.e. HP DL 380, Intel, Dell, Supermicro.  It is part of the information we collect during discovery but it is at the bottom of the page.

**Comment by galthaus** [comment]
In the planning meeting, we basically suggested a new part above memory/disks that is type.  That would be the easy fix for this.

**Comment by sjensen** [comment]
VRY Nice.  Exactly what I was looking for.
