### ISSUE TITLE
(UI) Powered off systems look like there was a problem

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#446]
When a system is discovered and correctly powered off the UI displays a number of items "To Do"  This makes it look like the system is stuck or did not complete.  This needs to be much more apparent.

**Comment by galthaus** [comment]
I tried hding the node roles of not active nodes, but that looks silly.  Maybe a black ground for node roles of not active nodes?

**Comment by sjensen** [comment]
we need someone with HW to test this puppy
