### ISSUE TITLE
6.5 install Chef Client fails

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#454]
//tmp/scriptjig-McDQRt/chef-client/01-install-client.sh@3(): which chef-client
which: no chef-client in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin)
//tmp/scriptjig-McDQRt/chef-client/01-install-client.sh@4(): [[ -f /etc/redhat-release ]]
//tmp/scriptjig-McDQRt/chef-client/01-install-client.sh@5(): yum -y makecache
Loaded plugins: security
Metadata Cache Created
//tmp/scriptjig-McDQRt/chef-client/01-install-client.sh@6(): yum install -y chef
Loaded plugins: security
Setting up Install Process
No package chef available.
Error: Nothing to do
/tmp/scriptjig-McDQRt/runner@58(): exit 1

**Comment by galthaus** [comment]
I think I need more details.  I just tried install 6.5 on my client and it fails in a different location.  lldpd is not available on 6.5.

**Comment by sjensen** [comment]
rerunning with the new RPMs

**Comment by sjensen** [comment]
Re-ran 2 more times.  Same results

/tmp/scriptjig-2nTQwP/runner@58(): tee /tmp/scriptjig-2nTQwP/logs/01-install-client.sh.log
//tmp/scriptjig-2nTQwP/chef-client/01-install-client.sh@3(): which chef-client
which: no chef-client in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin)
//tmp/scriptjig-2nTQwP/chef-client/01-install-client.sh@4(): [[ -f /etc/redhat-release ]]
//tmp/scriptjig-2nTQwP/chef-client/01-install-client.sh@5(): yum -y makecache
Loaded plugins: security
Metadata Cache Created
//tmp/scriptjig-2nTQwP/chef-client/01-install-client.sh@6(): yum install -y chef
Loaded plugins: security
Setting up Install Process
No package chef available.
Error: Nothing to do
/tmp/scriptjig-2nTQwP/runner@58(): exit 1

**Comment by sjensen** [comment]
looks like it does not have access to an external repo for chief.  Tried the cmds in the .sh script and they are unable to access the rpm

**Comment by sjensen** [comment]
Tried again.  Same error

Same Error...

which: no chef-client in (/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin)
//tmp/scriptjig-KsiOQs/chef-client/01-install-client.sh@4(): [[ -f /etc/redhat-release ]]
//tmp/scriptjig-KsiOQs/chef-client/01-install-client.sh@5(): yum -y makecache
Loaded plugins: security
Metadata Cache Created
//tmp/scriptjig-KsiOQs/chef-client/01-install-client.sh@6(): yum install -y chef
Loaded plugins: security
Setting up Install Process
No package chef available.
Error: Nothing to do
/tmp/scriptjig-KsiOQs/runner@58(): exit 1

Err: Warning: Permanently added '192.168.124.82' (RSA) to the list of known hosts.

**Comment by galthaus** [comment]
Very bizarre.  It works for me.  :-|  I get an lldpd error.

**Comment by sjensen** [comment]
[root@d08-00-27-19-94-8b ~]# yum -y makecache
Loaded plugins: security
base                                                     | 3.7 kB     00:00
crowbar-base                                             | 3.6 kB     00:00
extras                                                   | 3.4 kB     00:00
updates                                                  | 3.4 kB     00:00
Metadata Cache Created
[root@d08-00-27-19-94-8b ~]# yum install -y chef
Loaded plugins: security
Setting up Install Process
No package chef available.
Error: Nothing to do

**Comment by sjensen** [comment]
wahoo Works now!
