### ISSUE TITLE
Remove broken install wizard code

### ISSUE THREAD

**Issue by ravolt** [opencrowbar/core#470]
The install wizard code does not work and is not being maintained.  It should be removed.

**Comment by ravolt** [comment]
I had to leave the POST for the controller because it's used by BDD.  I moved it out of the UI routes and into the legacy routes.

**Comment by sjensen** [comment]
Verified that the system works correctly with this code gone.  Configurations are made in the UI and in the  proiduction.sh and install.sh scripts prior to running the install
