### ISSUE TITLE
Password reset is not available from CLI

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#472]
I would expect given the following users:

```
[
  {
    "id": 2,
    "email": "root@localhost.localdomain",
    "username": "machine-install",
    "is_admin": false,
    "created_at": "2015-02-16T21:56:03.582Z",
    "updated_at": "2015-02-16T21:56:03.586Z"
  },
  {
    "id": 1,
    "email": "",
    "username": "crowbar",
    "is_admin": true,
    "created_at": "2015-02-16T21:55:54.036Z",
    "updated_at": "2015-02-18T15:03:26.518Z"
  }
]
```

I could reset or set a password as follows:
```
$ crowbar users password 1
Please enter a new password >
Re-enter to confirm >

< System response here >
```

Instead there is not such available option

I tried seeing if help was missing, but the command looks just fine... from the users_controller:

```ruby
 add_help(:reset_password,[:id, :password, :password_confirmation],[:put])
 def reset_password
    #  TODO REFACTOR!
   ret = fetch_user
  respond_with(@user)  do |format|
    Rails.logger.debug("Reset password for user #{@user}")
    format.html do
# /\/\/\/\/\/\/
# end snippet
```

**Comment by sjensen** [comment]
@ravolt did you resolve the issue or just add BDD tests.  Trying to determine if this needs validation or was incorrectly closed.

**Comment by cloudedge** [comment]
I believe @dudymas confirmed it.  Consider it incorrectly closed.

On Mon, Mar 2, 2015 at 11:52 AM, SCOTT JENSEN <notifications@github.com>
wrote:

> @ravolt <https://github.com/ravolt> did you resolve the issue or just add
> BDD tests. Trying to determine if this needs validation or was incorrectly
> closed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencrowbar/core/issues/472#issuecomment-76762012>.
>



-- 
Rob
____________________________
Rob Hirschfeld, 512-773-7522
RackN CEO/Founder (rob@rackn.com)

I am in CENTRAL (-6) time
http://robhirschfeld.com
twitter: @zehicle, github: cloudedge & ravolt

**Comment by sjensen** [comment]
ok will reopen it

**Comment by dudymas** [comment]
sorry if I had folks close this early.
I wasn't able to get this working quite yet. I ended up just deleting the branch because when I tried to edit the bin, there seemed to be a 'TODO' on the password reset method and I simply didn't have the bandwidth to fully test the changes (and I'm pretty sure I didn't do a complete fix).

**Comment by VictorLowther** [comment]
Did 'crowbar users password 1 set <new password> not work for you?

**Comment by galthaus** [comment]
Validated that:
crowbar users password crowbar set fredfred 
does change the password.
Also validate that validation works as well.  Make sure length at least is 6.

This commit: fe0bf830238037ac6a9eabe316139e4cb98c3662
is good.  Should be in RPMs already.

**Comment by sjensen** [comment]
works well.  One security question.  Should we require that the user supply the current pwd in order to change?

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6czlh7-ta&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=RqlCnBIo&invitationId=6118771214124146689








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6czlh7-ta&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFGt7ZNS4oaLgAAAVOo-KOwzE5U0K7xWHcVu1B6-d61mlxMSPH-yXn5-u69E53z5qGJM-VjpsRnDSu_4Npkc6JxRqnmtUXincZtFq8NMRBdA20kML-xAotjZeG9zqbvne998lJdJa3gj_feIpDKN7DWrxZabHVyQGGXuymxUcCauArKQDEl1567e4WJb_eirJGd&eid=0-im6czlh7-ta


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6czlh7-ta&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-8iabc0-imfau4st-ef&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=RqlCnBIo&invitationID=6118771214124146689

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-8iabc0-imfau4st-ef&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=RqlCnBIo&invitationID=6118771214124146689





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-8iabc0-imfau4st-ef&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=-8iabc0-imfau4st-ef&loid=AQHkeCX4or8eBgAAAVPJ-EU4YGgOu0BUlSL5EVjfvK9Yi1FRM8SLaYiUdHz5sk0sYlyG45Jb807e81_X5UuduISUb3IGFcSaHYWJHxfzHEfaTQDAw06tKnishJIuMVj5dotMdWZfhCvyQ0HrnBhPLVIO4tNcjSjpLgpNib96VwldVFeRIL2q5j7CvnNhXr7G7C07

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-8iabc0-imfau4st-ef&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=-8iabc0-impb4wdm-92&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=RqlCnBIo&invitationID=6118771214124146689

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=-8iabc0-impb4wdm-92&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=RqlCnBIo&invitationID=6118771214124146689





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=-8iabc0-impb4wdm-92&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=-8iabc0-impb4wdm-92&loid=AQEbl2sCo3ohJQAAAVPuBMaseREIe12FjU0iAsFCin5WFEsHKTGTOv8THnyWIzaxOY32pLw9pJ7UbZNHqpTNQiepLUQ4sZRdzmCTquqhDn6MpQu2pTV06uxlX3hBqPA0s2O3hNImtwnzTK7XnV97XSMTX2FCHbQsq7UyUSgV3HRdTXtu4ZOQshg19jo9Esy7wZct

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=-8iabc0-impb4wdm-92&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
