### ISSUE TITLE
Close down Camshaft

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#487]
Cut a release for Camshaft and publish features
- Dev complete on all features
- Cut to "Release Branch"  Release branch will only take bug fixes
- Verify Documentation is up to date
- Verify all defects and mark as tested
- Cut to Master
- Generate RPMs
- Update VMs and videos
-  Celebrate!

**Comment by sjensen** [comment]
Current lost O' Features in Camshaft.

Camshaft
The Purpose of the Camshaft release is to integrate OpenCrowbar into existing Ops infrastructures.

Main Features:
Services Break-Out- introduces the concept of external services that OpenCrowbar can drive/integrate with removing the requirement that OpenCrowbar set up and manage those services.  In all cases the existing method that OpenCrowbar supported is still the default method.
DNS- Allows the direct use of an existing DNS infrastructure.  Previously OpenCrowbar would set up forwarders but required that it set up and manage it's own DNS infrastructure.
NTP- Allows the direct use of an existing NTP infrastructure.  Previously OpenCrowbar would set up Stratum forwarders but required that it set up and manage it's own NTP infrastructure.
DHCP- Allows the direct use of an existing DHCP infrastructure.  Previously OpenCrowbar could not work with another DHCP server.
Asynchronous actions-  Allows users to define external actions to "pause" the annealing process indefinitely.  This would be used when manual actions need to occur within the workflow.
Goardi replacement of Chef Server for internal bring up- Goiaradi (https://github.com/ctdk/goiardi).  This deals with a lot of dependency issues as well as some performance issues with Chef during initial bring up.  We intend this to have limited scope in the system.  Specifically to be used for initial bring up of OpenCrowbar Admin functions.  Developers or Users can of course use this or any version of chief that they wish.
UI Cleanup-  Ajax updates an minor UI reorganization.
Update Admin OS to CentOS-6.6 from CentOS-6.5.
Debian Support as a target OS
Many Bug Fixes and minor enhancements- See (https://github.com/opencrowbar/core/issues?q=is%3Aclosed+milestone%3ACamshaft.0+) for a full list.

**Comment by galthaus** [comment]
Release have been cut and RPMs updated.
