### ISSUE TITLE
Autogenerated readme.md is not updating

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#498]
Or it might.  Main indication that something is wrong is the link for RHEL/CentOS 6.5 Deployment Guide is not correct as the right doc is now RHEL/CentOS 6.6 Deployment Guide causing a dead link.  

This file states that it is autogenerated so I did not correct in the documentation

**Comment by galthaus** [comment]
What path did you start from?

**Comment by sjensen** [comment]
worked around for now
