### ISSUE TITLE
Release RPM will not install

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#499]
Looks like something was not updated in the amazon repo.

running:  wget --no-check-certificate -O - https://raw.githubusercontent.com/opencrowbar/core/develop/tools/crowbar-install.sh | source /dev/stdin --release
(as described in doc)  Returns the following error...
http://opencrowbar.s3-website-us-east-1.amazonaws.com/release/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: ocb-. Please verify its path and try again

verifying via browser gives 404.
switching to http://opencrowbar.s3-website-us-east-1.amazonaws.com/develop/repodata/repomd.xml returns the XML.  

Looks like the file needs to be made avail in the correct dir structure.

**Comment by galthaus** [comment]
You missed a parameter.
should be --release camshaft

**Comment by sjensen** [comment]
doc issue
