### ISSUE TITLE
Install failure chef

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#503]
//tmp/scriptjig-KEyqUZ/chef-server/01-install-chef-server.sh@12(): [[ -n '' ]]
//tmp/scriptjig-KEyqUZ/chef-server/01-install-chef-server.sh@16(): [[ -f /home/crowbar/.chef/crowbar.pem ]]
//tmp/scriptjig-KEyqUZ/chef-server/01-install-chef-server.sh@17(): echo 'Cannot find admin client key @ /home/crowbar/.chef/crowbar.pem!'
Cannot find admin client key @ /home/crowbar/.chef/crowbar.pem!
//tmp/scriptjig-KEyqUZ/chef-server/01-install-chef-server.sh@18(): exit 1
/tmp/scriptjig-KEyqUZ/runner@58(): exit 1

**Comment by cloudedge** [comment]
This is the same thing I get.  It appears to be a consul install fail

**Comment by zehicle** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Rob

Confirm that you know Rob: https://www.linkedin.com/e/v2?e=0-im6czaj1-k5&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=_2JSwi2-&invitationId=6118771211947294720








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-im6czaj1-k5&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGLP93Ddrg71QAAAVOo-Hv2Q_dZJXbwRw-zWc1WngosSMvQIDmAHICDIRU5Tqou_2QDHnaREkA1mwheu-g_OoGzNYyP6CkNMYMiZGVanl2Y2F_3ewlYAMX7iZL4NZRIuiOCf6K4ndw3vg6alIIh1Vrq3vCzFF5GUn-Rkj8vEZ6zxY7zvFaMlqKU69D9PfccLrz3&eid=0-im6czaj1-k5


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-im6czaj1-k5&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=d0xh68-imfatvm4-xf&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=_2JSwi2-&invitationID=6118771211947294720

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=d0xh68-imfatvm4-xf&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=_2JSwi2-&invitationID=6118771211947294720





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=d0xh68-imfatvm4-xf&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=d0xh68-imfatvm4-xf&loid=AQHBSH60ctCyyQAAAVPJ-EA0EwQv4ASz1GIFr1KwWJGmYCshQkLLswsdbkjbFtEAAg_zeR7KfsYQQPjWtdpAtooQh8GtwPhG2WHPP393xyYyWRZ99g4Nu6MqfsbIy7TSSOqWOn8yQFOXLD7PS4PlwaWXZv4KSXKa-McqKrqPs6iiFgFdrO1GhhPJlrMLVLexKdYY

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=d0xh68-imfatvm4-xf&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by zehicle** [comment]
Rob Hirschfeld would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=d0xh68-impb4txk-72&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=_2JSwi2-&invitationID=6118771211947294720

View Rob Hirschfeld&#39;s profile: https://www.linkedin.com/e/v2?e=d0xh68-impb4txk-72&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=_2JSwi2-&invitationID=6118771211947294720





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=d0xh68-impb4txk-72&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=d0xh68-impb4txk-72&loid=AQFsQKjHM63KmwAAAVPuBMVmqrZNYlMNoTGqrl9rGAMQ60gdZGCaCj344kLzpOQ0e1O1o1WKJ85qX1mVAk-uRctxVPti_AaqoD5YmBivjtvNrC0phcR4IJ4ZQ7VACOvsC8kITjyCtMuKQjIvDp_9P1OUW2mMrak8h_RuKPT09Wb4vI_tCdzW5xXmeUkic-FulgaE

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=d0xh68-impb4txk-72&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.
