### ISSUE TITLE
Consul in docker can get lost with proxy

### ISSUE THREAD

**Issue by galthaus** [opencrowbar/core#504]
When using docker with an inject proxy into the admin container, the Diplomat Consul library uses that proxy as gospel because it is part of the "init" process of docker.  It is not consistently overridden by restarting the crowbar service from the command line.

To fix this, a diplomat/faraday middleware should be added to the rails app that a minimum kills the discovered proxy or (more community friendly) uses the no_proxy env variable to detect if the proxy should be used in the first place.

I suspect that this is the bug that Victor was seeing with Consul on his setup.

**Comment by galthaus** [comment]
To work around this problem, unset http_proxy before running docker-admin.

**Comment by galthaus** [comment]
Issue fixed by #517

**Comment by sjensen** [comment]
Need someone with a Docker env to verify
