### ISSUE TITLE
External DNS issue

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#506]
Issue where when using an external DNS server.
Trying to install an OS fails with the following error

//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@29(): [[ -b /dev/name ]]
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@29(): continue
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@28(): read maj min blocks name
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@42(): true
///tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@43(): hostname -f
hostname: Unknown host
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@43(): curl -s -f -L -o /tmp/bootstate http://192.168.124.10:8091/nodes//bootstate
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@45(): sleep 1
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@42(): true
///tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@43(): hostname -f
hostname: Unknown host
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@43(): curl -s -f -L -o /tmp/bootstate http://192.168.124.10:8091/nodes//bootstate
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@45(): sleep 1
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@42(): true
///tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@43(): hostname -f
hostname: Unknown host
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@43(): curl -s -f -L -o /tmp/bootstate http://192.168.124.10:8091/nodes//bootstate
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@45(): sleep 1
//tmp/scriptjig-OQJpnU/provisioner-os-install/01-install-os.sh@42(): true

**Comment by sjensen** [comment]
reworked this defect

**Comment by galthaus** [comment]
We should set the hostname of the node as an attribute for this node_role to use.  Instead of using the hostname command to spin.  It would be safer then relying on DNS to find the hostname and domainname in the DNS system.

**Comment by galthaus** [comment]
Should add a provisioner_node_name attribute for this node role that is set in the on_proposed function.  or maybe based upon the node.name field and added to sys_data on the fly.

**Comment by galthaus** [comment]
Fixed by #508
