### ISSUE TITLE
centos7 iso may have changed

### ISSUE THREAD

**Issue by galthaus** [opencrowbar/core#523]
The default centos 7 iso may have disappears.  Need to update OCB on supporting 1503.

**Comment by galthaus** [comment]
This will need to be in master and develop.  Update the install script and docs.

**Comment by sjensen** [comment]
Agreed.  The new version is CentOS-7-x86_64-DVD-1503-01.iso   Sigh, gutta love it when they do not rev the version

**Comment by sjensen** [comment]
Making this HotFix worthy
