### ISSUE TITLE
Ubuntu 14.04 changed upstream

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#532]
Canonical has updated Ubuntu from 
ubuntu-14.04.1-server-amd64.iso
to
ubuntu-14.04.2-server-amd64.iso

**Comment by sjensen** [comment]
Did someone pick this up?  If so pls claim.  Need a determination on whether or not this is hotfix worthy.

**Comment by galthaus** [comment]
Rob seems to have moved it.
