### ISSUE TITLE
Saltstack on CentOS 6 needs updates repo

### ISSUE THREAD

**Issue by galthaus** [opencrowbar/core#551]
CentOS moved the PyYAML rpm from epel to os-updates.  This breaks the CentOS 6 based install.

Add to /etc/yum.repos.d/os-updates.repo
[os-updates]
name=CentOS 6 Updates
baseurl=http://mirror.centos.org/centos-6/6/updates/x86_64/
enables=1
gpgcheck=0

**Comment by galthaus** [comment]
Saltstack now seems to be working for all OSes except Ubuntu 12.04 and Debian 78.  Not sure Saltstack is supported there.

**Comment by galthaus** [comment]
No changes were required to fix this.  We may want to look at debian 7.8 at some point.  It might be supported by saltstack.

**Comment by sjensen** [comment]
looks gd
