### ISSUE TITLE
Docker Machine Driver

### ISSUE THREAD

**Issue by zehicle** [opencrowbar/core#601]
Not really a Crowbar feature, this is an integration with the Docker/Machine mechanism.  It's worth tracking here so that we can see if there are bugs or features that are driven by this work.

**Comment by VictorLowther** [comment]
This shoudl be refactored to split out the Crowbar API pieces into their own library that the docker machine code can ipmort.

**Comment by zehicle** [comment]
Done.  I put the client in https://github.com/rackn/ocb-client-go
