### ISSUE TITLE
altering base-images should be attibutes

### ISSUE THREAD

**Issue by dudymas** [opencrowbar/core#613]
One would expect to be able to upload changes to the chef server and have new images go up with that, considering available images are tightly coupled and managed by the provisioner.

Instead, if one changes the images, the database and/or attributes must be managed separately for updating the base images.

The proposed fix would be to move the base images role template out of ```chef/roles/provisioner-base-images/role-template.json```

tagging @VictorLowther since he mentioned this in the gitter.
tagging @galthaus since he mentioned the 'OS bundles' feature fixing this.

**Comment by galthaus** [comment]
These are now defined as an attribute that can be modified in the provisioner.yml file or from the cli.

**Comment by dudymas** [comment]
Got it! Thank you. We're stable for a month or so, but might get to try this out when we get another blade in.
