### ISSUE TITLE
Number of disks is showing as 0

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#619]
![image](https://cloud.githubusercontent.com/assets/1200679/7891747/14647dc8-061d-11e5-86f5-e7a33d36a1e6.png)

**Comment by VictorLowther** [comment]
Does it have anything under the disks attribute?

**Comment by sjensen** [comment]
Yes it shows a lot of info there
 something like....


[{"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_CD-ROM_VB2-01700376"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:01.1/ata2/host1/target1:0:0/1:0:0:0/block/sr0", "readonly"=>false, "removable"=>true, "size"=>1073741312.0, "ssd"=>false, "unique_name"=>"/dev/disk/by-id/ata-VBOX_CD-ROM_VB2-01700376", "usb"=>false, "used"=>false, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VB754b301f-fce438fe"], "partitioned"=>true, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/ata3/host2/target2:0:0/2:0:0:0/block/sda", "readonly"=>false, "removable"=>false, "size"=>21474836480.0, "ssd"=>true, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VB754b301f-fce438fe", "usb"=>false, "used"=>true, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VBf98e5d30-30a84b0e"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/ata4/host3/target3:0:0/3:0:0:0/block/sdb", "readonly"=>false, "removable"=>false, "size"=>8589934592.0, "ssd"=>true, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VBf98e5d30-30a84b0e", "usb"=>false, "used"=>false, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VBf9967018-a173a0da"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/ata5/host4/target4:0:0/4:0:0:0/block/sdc", "readonly"=>false, "removable"=>false, "size"=>8589934592.0, "ssd"=>false, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VBf9967018-a173a0da", "usb"=>false, "used"=>false, "virtual"=>false}, {"formatted"=>false, "held"=>false, "ids"=>["/dev/disk/by-id/ata-VBOX_HARDDISK_VB33604c23-4093dd9b"], "partitioned"=>false, "path"=>"/sys/devices/pci0000:00/0000:00:0d.0/ata6/host5/target5:0:0/5:0:0:0/block/sdd", "readonly"=>false, "removable"=>false, "size"=>8589934592.0, "ssd"=>false, "unique_name"=>"/dev/disk/by-id/ata-VBOX_HARDDISK_VB33604c23-4093dd9b", "usb"=>false, "used"=>false, "virtual"=>false}]

**Comment by VictorLowther** [comment]
OK, that is what it is supposed to show there.  The other attribute is one that is calculated straight from ohai data that I should fix up.
