### ISSUE TITLE
Chef client failure on ubuntu 12.04

### ISSUE THREAD

**Issue by sjensen** [opencrowbar/core#651]
Trying to deploy Ubuntu 12.04 recieves the following error after installing and trying to install the chef client role

Hit http://us.archive.ubuntu.com precise-updates/multiverse Translation-en
Hit http://us.archive.ubuntu.com precise-updates/restricted Translation-en
Hit http://us.archive.ubuntu.com precise-updates/universe Translation-en
Fetched 4872 kB in 3s (1554 kB/s)
Reading package lists...
W: GPG error: http://extras.ubuntu.com precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 16126D3A3E5C1192
W: GPG error: http://ppa.launchpad.net precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4759FA960E27C0A6
W: GPG error: http://apt.postgresql.org precise-pgdg Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 7FCC7D46ACCC4CF8
W: GPG error: http://download.draios.com stable-amd64/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 74490FD6EC51E8C4
//tmp/scriptjig-fb3hYi/chef-client/01-install-client.sh@33(): apt-get -y --force-yes install chef
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package chef
/tmp/scriptjig-fb3hYi/runner@58(): exit 1

Err: Warning: Permanently added '192.168.124.81' (RSA) to the list of known hosts.

**Comment by VictorLowther** [comment]
Should be fixed by #670
