### ISSUE TITLE
RAID file links now incorrect in crowbar-install.sh script

### ISSUE THREAD

**Issue by wdennis** [opencrowbar/core#758]
The links referenced in the `crowbar-install.sh` script are now incorrect; going to either of them now redirects to http://www.avagotech.com/ (the company that acquired LSI in 2014.) The section needing update is:

    if [[ $WITH_HARDWARE = 'YES' ]]; then
        mkdir -p /tftpboot/files/raid
    
        echo "Remember to populate /tftpboot/files/raid"
        echo "See: https://github.com/opencrowbar/hardware/tree/master/doc"
        echo ""
        echo "Files can be pulled from these links after accepting licenses."
        echo " http://www.lsi.com/downloads/Public/Host%20Bus%20Adapters/Host%20Bus%20Adapters%20Common%20Files/SAS_SATA_6G_P19/SAS2IRCU_P19.zip"
        echo " http://www.lsi.com/downloads/Public/RAID%20Controllers/RAID%20Controllers%20Common%20Files/8.07.14_MegaCLI.zip"
        echo ""
    fi

File downloads may now be found at: http://www.avagotech.com/support/download-search
However, would need to know the new names of the files that need to be downloaded and then uploaded to the OCB admin server.

**Comment by galthaus** [comment]
I update this in the hardware and core trees for Drill.
